<?php

namespace LibretaBundle\Repository;

/**
 * libretaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class libretaRepository extends \Doctrine\ORM\EntityRepository
{
}
