<?php

namespace LibretaBundle\Repository;

/**
 * notaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class notaRepository extends \Doctrine\ORM\EntityRepository
{
}
